/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIFlowPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "sk-itnytfacpeobkvireovadmsrbonrgemrsnfgsqvhesjtyppz",
  model: "deepseek-ai/DeepSeek-V3",
  // 确认你的 API 支持此模型名称
  sourceFolder: "00-Inbox",
  destinationFolder: "Knowledge Base",
  templatePath: "90-System/Templates/\u6A21\u677F/\u8BB2\u7A3F\u6A21\u677F.md",
  systemPrompt: `\u4F60\u662F\u4E00\u4E2A\u8D44\u6DF1\u7684\u77E5\u8BC6\u7BA1\u7406\u4E13\u5BB6\u548C\u5185\u5BB9\u5206\u6790\u5E08\u3002\u7528\u6237\u7684\u8F93\u5165\u662F\u4E00\u7BC7\u3010\u8BB2\u7A3F/\u901F\u8BB0\u3011\u3002
\u4F60\u7684\u4EFB\u52A1\u662F\u6DF1\u5EA6\u5206\u6790\u5185\u5BB9\uFF0C\u5E76\u5C06\u5176\u91CD\u6784\u4E3A\u7ED3\u6784\u5316\u7684\u77E5\u8BC6\u6587\u6863\u3002

\u8BF7\u4E25\u683C\u6309\u7167\u4EE5\u4E0B JSON \u683C\u5F0F\u8FD4\u56DE\u6570\u636E\uFF08\u4E0D\u8981\u5305\u542B markdown \u4EE3\u7801\u5757\u6807\u8BB0\uFF0C\u76F4\u63A5\u8FD4\u56DE\u7EAF JSON\uFF09\uFF1A
{
  "suggested_tags": "\u8BF7\u63D0\u53D63-5\u4E2A\u6838\u5FC3\u5206\u7C7B\u6807\u7B7E\uFF0C\u683C\u5F0F\u5FC5\u987B\u4E25\u683C\u4E3A YAML \u5217\u8868\u5B57\u7B26\u4E32\u3002\u6807\u7B7E\u5FC5\u987B\u5305\u542B\uFF1A1) \u6D89\u53CA\u7684\u9886\u57DF\uFF08\u5982\uFF1A\u5FC3\u7406\u5B66/\u7F16\u7A0B/\u7BA1\u7406/\u8425\u9500\u7B49\uFF092) \u5982\u679C\u8BB2\u7A3F\u4E2D\u63D0\u5230\u5177\u4F53\u7684 AI \u6A21\u578B\u540D\u79F0\uFF08\u5982 GPT-4, Claude, Midjourney \u7B49\uFF09\uFF0C\u5FC5\u987B\u6DFB\u52A0\u5BF9\u5E94\u6807\u7B7E\uFF1B\u5982\u679C\u6CA1\u6709\u63D0\u5230 AI \u6A21\u578B\u5219\u4E0D\u52A0\u3002\u4F8B\u5982\uFF1A'  - \u5FC3\u7406\u5B66\\n  - \u8BA4\u77E5\u79D1\u5B66\\n  - GPT-4\\n  - \u6C9F\u901A\u6280\u5DE7' (\u6CE8\u610F\u6362\u884C\u7B26\u548C\u7F29\u8FDB)",
  "analysis_table": "\u751F\u6210\u4E00\u4E2A Markdown \u8868\u683C\uFF0C\u603B\u7ED3\u5168\u6587\u3002\u8868\u683C\u5217\u5934\u9700\u5305\u542B\uFF1A[\u6838\u5FC3\u8BAE\u9898, \u5173\u952E\u6982\u5FF5(3\u4E2A), \u60C5\u611F/\u57FA\u8C03, \u9002\u7528\u573A\u666F, \u91CD\u8981\u7A0B\u5EA6(1-5\u661F)]",
  "detailed_content": "\u8BE6\u7EC6\u7684\u6B63\u6587\u5206\u6790\uFF0C\u8981\u6C42\u5185\u5BB9\u5145\u5B9E\u3001\u7EC6\u8282\u4E30\u5BCC\uFF0C\u4E0D\u8981\u8FC7\u5EA6\u6982\u62EC\u3002\u8BF7\u6309\u903B\u8F91\u5206\u7AE0\u8282\uFF08\u4F7F\u7528 ##, ### \u6807\u9898\uFF09\uFF0C\u5FC5\u987B\u5305\u542B\u4EE5\u4E0B\u90E8\u5206\uFF1A1) \u80CC\u666F\u4ECB\u7ECD\uFF08\u8BB2\u8005\u80CC\u666F\u3001\u6F14\u8BB2\u573A\u5408\u3001\u6838\u5FC3\u95EE\u9898\uFF09\uFF0C2) \u6838\u5FC3\u89C2\u70B9\u68B3\u7406\uFF08\u9010\u4E00\u8BE6\u7EC6\u9610\u8FF0\u6BCF\u4E2A\u91CD\u8981\u89C2\u70B9\uFF0C\u5305\u542B\u8BBA\u636E\u548C\u63A8\u7406\u8FC7\u7A0B\uFF09\uFF0C3) \u6848\u4F8B\u5206\u6790\uFF08\u5BF9\u6BCF\u4E2A\u6848\u4F8B\u8FDB\u884C\u8BE6\u7EC6\u89E3\u8BFB\uFF0C\u5305\u62EC\u5177\u4F53\u505A\u6CD5\u3001\u6548\u679C\u6570\u636E\u3001\u5173\u952E\u542F\u793A\uFF09\uFF0C4) \u65B9\u6CD5\u8BBA\u63D0\u70BC\uFF08\u603B\u7ED3\u53EF\u590D\u7528\u7684\u65B9\u6CD5\u548C\u6846\u67B6\uFF09\uFF0C5) \u91D1\u53E5\u6458\u5F55\uFF08\u5F15\u7528\u539F\u8BDD\u4E2D\u7684\u7CBE\u5F69\u8868\u8FF0\uFF09\u3002\u4FDD\u6301\u4E13\u4E1A\u3001\u4E66\u9762\u5316\uFF0C\u4F46\u8981\u4FDD\u7559\u91CD\u8981\u7EC6\u8282\u548C\u5177\u4F53\u4FE1\u606F\u3002\u6BCF\u4E2A\u90E8\u5206\u81F3\u5C11\u9700\u8981150-200\u5B57\uFF0C\u603B\u5B57\u6570\u4E0D\u5C11\u4E8E800\u5B57\u3002",
  "action_items": "\u57FA\u4E8E\u5185\u5BB9\u63D0\u70BC\u7684\u53EF\u6267\u884C\u5EFA\u8BAE\u6E05\u5355\uFF08Markdown \u5217\u8868\u683C\u5F0F\uFF09\uFF0C\u6BCF\u6761\u5EFA\u8BAE\u8981\u5177\u4F53\u53EF\u64CD\u4F5C\uFF0C\u907F\u514D\u7A7A\u6CDB\u3002"
}`
};
var AIFlowPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "process-lecture-note",
      name: "\u2728 \u5C06\u5F53\u524D\u8BB2\u7A3F\u6574\u7406\u81F3\u77E5\u8BC6\u5E93 (\u8868\u683C+\u6DF1\u5EA6\u5206\u6790)",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile)
          return false;
        const isInSource = activeFile.path.startsWith(this.settings.sourceFolder);
        if (checking)
          return isInSource;
        this.processNote(activeFile);
        return true;
      }
    });
    this.addSettingTab(new AIFlowSettingTab(this.app, this));
  }
  async processNote(sourceFile) {
    new import_obsidian.Notice(`\u{1F680} \u5F00\u59CB\u6574\u7406\u8BB2\u7A3F: ${sourceFile.basename}`);
    new import_obsidian.Notice(`\u{1F4D6} (1/6) \u6B63\u5728\u8BFB\u53D6\u6E90\u6587\u4EF6...`);
    const sourceContent = await this.app.vault.read(sourceFile);
    const contentLength = sourceContent.length;
    new import_obsidian.Notice(`\u2705 \u5DF2\u8BFB\u53D6 ${contentLength} \u5B57\u7B26`);
    try {
      new import_obsidian.Notice(`\u{1F916} (2/6) \u6B63\u5728\u8C03\u7528 DeepSeek AI \u5206\u6790...`);
      const startTime = Date.now();
      const aiResult = await this.callSiliconFlow(sourceContent);
      const elapsed = ((Date.now() - startTime) / 1e3).toFixed(1);
      new import_obsidian.Notice(`\u2705 AI \u5206\u6790\u5B8C\u6210 (\u8017\u65F6 ${elapsed} \u79D2)`);
      new import_obsidian.Notice(`\u{1F4CB} (3/6) \u6B63\u5728\u89E3\u6790 AI \u7ED3\u679C...`);
      let aiData;
      try {
        const cleanJson = aiResult.replace(/```json/g, "").replace(/```/g, "").trim();
        aiData = JSON.parse(cleanJson);
      } catch (e) {
        console.error("JSON\u89E3\u6790\u5931\u8D25", aiResult);
        new import_obsidian.Notice("\u26A0\uFE0F AI \u8FD4\u56DE\u683C\u5F0F\u5F02\u5E38\uFF0C\u8BF7\u67E5\u770B\u63A7\u5236\u53F0\u65E5\u5FD7");
        return;
      }
      new import_obsidian.Notice(`\u2705 \u6570\u636E\u89E3\u6790\u6210\u529F`);
      new import_obsidian.Notice(`\u{1F4C4} (4/6) \u6B63\u5728\u8BFB\u53D6\u6A21\u677F...`);
      const templateFile = this.app.vault.getAbstractFileByPath(this.settings.templatePath);
      if (!(templateFile instanceof import_obsidian.TFile)) {
        new import_obsidian.Notice(`\u274C \u627E\u4E0D\u5230\u6A21\u677F\u6587\u4EF6: ${this.settings.templatePath}`);
        return;
      }
      let templateContent = await this.app.vault.read(templateFile);
      const platform = this.detectPlatform(sourceFile.path);
      const sourceTag = platform ? `  - source/${platform}
` : "";
      new import_obsidian.Notice(`\u{1F3F7}\uFE0F \u8BC6\u522B\u6765\u6E90: ${platform}`);
      new import_obsidian.Notice(`\u270D\uFE0F  (5/6) \u6B63\u5728\u751F\u6210\u6587\u6863...`);
      const finalContent = templateContent.replace(/\{\{title\}\}/g, sourceFile.basename).replace(/\{\{date\}\}/g, (/* @__PURE__ */ new Date()).toISOString().split("T")[0]).replace(/\{\{model_name\}\}/g, this.settings.model).replace(/\{\{source_file\}\}/g, sourceFile.path).replace(/\{\{SOURCE_TAG\}\}/g, sourceTag).replace(/\{\{AI_TAGS\}\}/g, aiData.suggested_tags || "  - \u5F85\u5206\u7C7B").replace(/\{\{AI_TABLE\}\}/g, aiData.analysis_table || "\u8868\u683C\u751F\u6210\u5931\u8D25").replace(/\{\{AI_DETAILED_CONTENT\}\}/g, aiData.detailed_content || "\u751F\u6210\u5931\u8D25").replace(/\{\{AI_ACTION_ITEMS\}\}/g, aiData.action_items || "\u65E0");
      new import_obsidian.Notice(`\u{1F4BE} (6/6) \u6B63\u5728\u4FDD\u5B58\u6587\u4EF6...`);
      if (!this.app.vault.getAbstractFileByPath(this.settings.destinationFolder)) {
        await this.app.vault.createFolder(this.settings.destinationFolder);
      }
      const destPath = `${this.settings.destinationFolder}/${sourceFile.basename}_AI.md`;
      const existFile = this.app.vault.getAbstractFileByPath(destPath);
      if (existFile) {
        await this.app.vault.delete(existFile);
      }
      const newFile = await this.app.vault.create(destPath, finalContent);
      new import_obsidian.Notice(`\u{1F389} \u8BB2\u7A3F\u6574\u7406\u5B8C\u6210\uFF01\u5DF2\u4FDD\u5B58\u81F3 Knowledge Base`);
      const wordCount = finalContent.length;
      const lineCount = finalContent.split("\n").length;
      console.log(`\u751F\u6210\u6587\u4EF6\u7EDF\u8BA1: ${wordCount} \u5B57\u7B26, ${lineCount} \u884C`);
      this.app.workspace.getLeaf("tab").openFile(newFile);
    } catch (error) {
      new import_obsidian.Notice(`\u5904\u7406\u51FA\u9519: ${error.message}`);
      console.error(error);
    }
  }
  async callSiliconFlow(content) {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.siliconflow.cn/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${this.settings.apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: this.settings.model,
        messages: [
          { role: "system", content: this.settings.systemPrompt },
          { role: "user", content }
        ],
        stream: false,
        temperature: 0.5,
        // 稍微降低温度，让分析更严谨
        response_format: { type: "json_object" }
      })
    });
    if (response.status !== 200) {
      throw new Error(`API Error: ${response.status}`);
    }
    return response.json.choices[0].message.content;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 自动检测来源平台
  detectPlatform(filePath) {
    if (filePath.includes("01-B\u7AD9") || filePath.includes("01-bilibili")) {
      return "B\u7AD9";
    } else if (filePath.includes("02-\u6296\u97F3") || filePath.includes("02-douyin")) {
      return "\u6296\u97F3";
    } else if (filePath.includes("03-\u5C0F\u7EA2\u4E66") || filePath.includes("03-xiaohongshu")) {
      return "\u5C0F\u7EA2\u4E66";
    } else if (filePath.includes("01-\u8BB2\u7A3F") || filePath.includes("01-lecture")) {
      return "\u8BB2\u7A3F";
    } else if (filePath.includes("00-\u4E34\u65F6")) {
      return "\u4E34\u65F6";
    }
    return "\u672A\u77E5\u6765\u6E90";
  }
};
var AIFlowSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "AI Flow \u8BB2\u7A3F\u6DF1\u5EA6\u5206\u6790\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("SiliconFlow API Key").addText((text) => text.setPlaceholder("Enter your key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u63A8\u8350\u4F7F\u7528 DeepSeek-V3 \u6216 R1").addText((text) => text.setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6E90\u6587\u4EF6\u5939").addText((text) => text.setValue(this.plugin.settings.sourceFolder).onChange(async (value) => {
      this.plugin.settings.sourceFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u76EE\u6807\u6587\u4EF6\u5939").addText((text) => text.setValue(this.plugin.settings.destinationFolder).onChange(async (value) => {
      this.plugin.settings.destinationFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6A21\u677F\u8DEF\u5F84").addText((text) => text.setValue(this.plugin.settings.templatePath).onChange(async (value) => {
      this.plugin.settings.templatePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF\u63D0\u793A\u8BCD (System Prompt)").setDesc("\u4FEE\u6539 AI \u7684\u6307\u4EE4\u903B\u8F91").addTextArea((text) => text.setPlaceholder("\u8F93\u5165\u7CFB\u7EDF\u63D0\u793A\u8BCD...").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
      this.plugin.settings.systemPrompt = value;
      await this.plugin.saveSettings();
    }));
  }
};
